# This is a basic workflow to help you get started with Actions

name: CI Integration


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - staging
          - production

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job handles environment-specific deployment
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Deploy to Environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment"

  # This job handles basic CI tasks
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runner's shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runner's shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
